# Generated by Django 5.2.15 on 2026-06-05 04:58

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2024)),
                ('target_duration', models.DurationField(default=datetime.timedelta(days=2, seconds=43200))),
                ('actual_duration', models.DurationField(default=datetime.timedelta(0))),
                ('achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('paused_time', models.DateTimeField(blank=True, null=True)),
                ('total_paused_duration', models.DurationField(default=datetime.timedelta(0))),
                ('is_paused', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='target_hours',
        ),
        migrations.AddField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='actual_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='target_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=72000)),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'status'], name='tracker_stu_user_id_7b332d_idx'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timersession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='tracker.subject'),
        ),
        migrations.AddField(
            model_name='timersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monthlygoal',
            unique_together={('user', 'month', 'year')},
        ),
    ]
